### ISSUE TITLE
Missing Table Creation

### ISSUE THREAD

**Issue by etaylor77** [b-zylka/LTHCv2#1]
Query: CREATE VIEW `v_plugin_lthc_score_client` AS (select `clients`.`ClientID` AS `clientid`,`clients`.`Name` AS `Client Name`,`v_extr...

Error Code: 1146
Table 'labtech.vxr_healthcheck' doesn't exist

Query: CREATE VIEW `v_plugin_lthc_score_computer` AS (select `computers`.`ComputerID` AS `computerid`,`computers`.`Name` AS `Computer_N...

Error Code: 1146
Table 'labtech.vxr_healthcheck' doesn't exist

**Comment by b-zylka** [comment]
I'll update the sql script as LT 11 no longer uses it creates that view.

**Comment by etaylor77** [comment]
Good day,

As I am still using 10.5 and probably will for some time ahead, can you consider changes for this? Thanks for your time.

**Comment by etaylor77** [comment]
issue resolved in fork
